// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evqukyginezfsydkeebd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2cXVreWdpbmV6ZnN5ZGtlZWJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDgzNjQsImV4cCI6MjA2MDEyNDM2NH0.0kKmf8FlNReNX-oxj2Ri0Im5a3OTJdQOIdDv6C9Cd9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);